/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FortunaGiveaway {
  export type CauseStruct = {
    name: string;
    description: string;
    beneficiary: AddressLike;
    entryPrice: BigNumberish;
    totalDonated: BigNumberish;
    totalEntries: BigNumberish;
    drawTime: BigNumberish;
    active: boolean;
    drawn: boolean;
    winner: AddressLike;
    prizeType: BigNumberish;
    prizeAmount: BigNumberish;
  };

  export type CauseStructOutput = [
    name: string,
    description: string,
    beneficiary: string,
    entryPrice: bigint,
    totalDonated: bigint,
    totalEntries: bigint,
    drawTime: bigint,
    active: boolean,
    drawn: boolean,
    winner: string,
    prizeType: bigint,
    prizeAmount: bigint
  ] & {
    name: string;
    description: string;
    beneficiary: string;
    entryPrice: bigint;
    totalDonated: bigint;
    totalEntries: bigint;
    drawTime: bigint;
    active: boolean;
    drawn: boolean;
    winner: string;
    prizeType: bigint;
    prizeAmount: bigint;
  };
}

export interface FortunaGiveawayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "causeCount"
      | "causes"
      | "createCause"
      | "donate"
      | "emergencyWithdraw"
      | "entries"
      | "feeRecipient"
      | "getCause"
      | "getEntries"
      | "owner"
      | "platformFeePercent"
      | "rawFulfillRandomWords"
      | "renounceOwnership"
      | "requestDraw"
      | "setFeeRecipient"
      | "setPlatformFee"
      | "toggleCauseActive"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CauseCreated"
      | "CharityPaid"
      | "DonationReceived"
      | "DrawRequested"
      | "OwnershipTransferred"
      | "WinnerSelected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "causeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "causes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCause",
    values: [
      string,
      string,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entries",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCause",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomWords",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestDraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleCauseActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "causeCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "causes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEntries", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleCauseActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CauseCreatedEvent {
  export type InputTuple = [
    causeId: BigNumberish,
    name: string,
    beneficiary: AddressLike,
    entryPrice: BigNumberish,
    drawTime: BigNumberish,
    prizeType: BigNumberish
  ];
  export type OutputTuple = [
    causeId: bigint,
    name: string,
    beneficiary: string,
    entryPrice: bigint,
    drawTime: bigint,
    prizeType: bigint
  ];
  export interface OutputObject {
    causeId: bigint;
    name: string;
    beneficiary: string;
    entryPrice: bigint;
    drawTime: bigint;
    prizeType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CharityPaidEvent {
  export type InputTuple = [
    causeId: BigNumberish,
    beneficiary: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    causeId: bigint,
    beneficiary: string,
    amount: bigint
  ];
  export interface OutputObject {
    causeId: bigint;
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonationReceivedEvent {
  export type InputTuple = [
    causeId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish,
    entries: BigNumberish
  ];
  export type OutputTuple = [
    causeId: bigint,
    donor: string,
    amount: bigint,
    entries: bigint
  ];
  export interface OutputObject {
    causeId: bigint;
    donor: string;
    amount: bigint;
    entries: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DrawRequestedEvent {
  export type InputTuple = [causeId: BigNumberish, requestId: BigNumberish];
  export type OutputTuple = [causeId: bigint, requestId: bigint];
  export interface OutputObject {
    causeId: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerSelectedEvent {
  export type InputTuple = [
    causeId: BigNumberish,
    winner: AddressLike,
    prizeAmount: BigNumberish
  ];
  export type OutputTuple = [
    causeId: bigint,
    winner: string,
    prizeAmount: bigint
  ];
  export interface OutputObject {
    causeId: bigint;
    winner: string;
    prizeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FortunaGiveaway extends BaseContract {
  connect(runner?: ContractRunner | null): FortunaGiveaway;
  waitForDeployment(): Promise<this>;

  interface: FortunaGiveawayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  causeCount: TypedContractMethod<[], [bigint], "view">;

  causes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint,
        bigint
      ] & {
        name: string;
        description: string;
        beneficiary: string;
        entryPrice: bigint;
        totalDonated: bigint;
        totalEntries: bigint;
        drawTime: bigint;
        active: boolean;
        drawn: boolean;
        winner: string;
        prizeType: bigint;
        prizeAmount: bigint;
      }
    ],
    "view"
  >;

  createCause: TypedContractMethod<
    [
      _name: string,
      _description: string,
      _beneficiary: AddressLike,
      _entryPrice: BigNumberish,
      _drawTime: BigNumberish,
      _prizeType: BigNumberish,
      _prizeAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  donate: TypedContractMethod<[causeId: BigNumberish], [void], "payable">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  entries: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getCause: TypedContractMethod<
    [causeId: BigNumberish],
    [FortunaGiveaway.CauseStructOutput],
    "view"
  >;

  getEntries: TypedContractMethod<[causeId: BigNumberish], [string[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  rawFulfillRandomWords: TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestDraw: TypedContractMethod<
    [causeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [_newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  toggleCauseActive: TypedContractMethod<
    [causeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "causeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "causes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint,
        bigint
      ] & {
        name: string;
        description: string;
        beneficiary: string;
        entryPrice: bigint;
        totalDonated: bigint;
        totalEntries: bigint;
        drawTime: bigint;
        active: boolean;
        drawn: boolean;
        winner: string;
        prizeType: bigint;
        prizeAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCause"
  ): TypedContractMethod<
    [
      _name: string,
      _description: string,
      _beneficiary: AddressLike,
      _entryPrice: BigNumberish,
      _drawTime: BigNumberish,
      _prizeType: BigNumberish,
      _prizeAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<[causeId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "entries"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCause"
  ): TypedContractMethod<
    [causeId: BigNumberish],
    [FortunaGiveaway.CauseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntries"
  ): TypedContractMethod<[causeId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rawFulfillRandomWords"
  ): TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestDraw"
  ): TypedContractMethod<[causeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[_newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleCauseActive"
  ): TypedContractMethod<[causeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CauseCreated"
  ): TypedContractEvent<
    CauseCreatedEvent.InputTuple,
    CauseCreatedEvent.OutputTuple,
    CauseCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CharityPaid"
  ): TypedContractEvent<
    CharityPaidEvent.InputTuple,
    CharityPaidEvent.OutputTuple,
    CharityPaidEvent.OutputObject
  >;
  getEvent(
    key: "DonationReceived"
  ): TypedContractEvent<
    DonationReceivedEvent.InputTuple,
    DonationReceivedEvent.OutputTuple,
    DonationReceivedEvent.OutputObject
  >;
  getEvent(
    key: "DrawRequested"
  ): TypedContractEvent<
    DrawRequestedEvent.InputTuple,
    DrawRequestedEvent.OutputTuple,
    DrawRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WinnerSelected"
  ): TypedContractEvent<
    WinnerSelectedEvent.InputTuple,
    WinnerSelectedEvent.OutputTuple,
    WinnerSelectedEvent.OutputObject
  >;

  filters: {
    "CauseCreated(uint256,string,address,uint256,uint256,uint8)": TypedContractEvent<
      CauseCreatedEvent.InputTuple,
      CauseCreatedEvent.OutputTuple,
      CauseCreatedEvent.OutputObject
    >;
    CauseCreated: TypedContractEvent<
      CauseCreatedEvent.InputTuple,
      CauseCreatedEvent.OutputTuple,
      CauseCreatedEvent.OutputObject
    >;

    "CharityPaid(uint256,address,uint256)": TypedContractEvent<
      CharityPaidEvent.InputTuple,
      CharityPaidEvent.OutputTuple,
      CharityPaidEvent.OutputObject
    >;
    CharityPaid: TypedContractEvent<
      CharityPaidEvent.InputTuple,
      CharityPaidEvent.OutputTuple,
      CharityPaidEvent.OutputObject
    >;

    "DonationReceived(uint256,address,uint256,uint256)": TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;
    DonationReceived: TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;

    "DrawRequested(uint256,uint256)": TypedContractEvent<
      DrawRequestedEvent.InputTuple,
      DrawRequestedEvent.OutputTuple,
      DrawRequestedEvent.OutputObject
    >;
    DrawRequested: TypedContractEvent<
      DrawRequestedEvent.InputTuple,
      DrawRequestedEvent.OutputTuple,
      DrawRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WinnerSelected(uint256,address,uint256)": TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
    WinnerSelected: TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
  };
}
